name: parser
description: A web scrapy application
version: 1.0.0
repository: https://github.com/warioddly/heritage

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  html: ^0.15.4
  http: ^1.2.0
  path_provider: ^2.1.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
